### ISSUE TITLE
Further train the model

### ISSUE THREAD

**Issue by tayalkshitij** [ternaus/TernausNetV2#14]
I am using TernausNetV2 for my project. Although it is doing phenomenal job in most of the places, there are some areas in Khartoum where it performs very poorly. I have the training data for the building detection from SpaceNet dataset as well as data from other sources and would like to train your model further. 

What is the correct way to train your model further using existing weights rather than starting fresh ?

**Comment by ternaus** [comment]
You may try to adapt this pipeline for your case:

https://github.com/ternaus/robot-surgery-segmentation
