### ISSUE TITLE
Error:  cannot import name '_ext'

### ISSUE THREAD

**Issue by PeterXiaoGuo** [ternaus/TernausNetV2#2]
hi, 

Thank you for your v2 TernausNet, I appreciate your paper on arXiv and I follow your several papers and like the clear logic and intuition.

When I run this code in Demo file, I face an error 
**ImportError: cannot import name '_ext'**
during running this command: 
`from models.ternausnet2 import TernausNetV2`

I check it and find it results from this line:
`from . import _ext`
from **modules\functions.py**

I google it and cannot figure how **from . import _ext** works at all.

Could you please give me some hint to solve this issue?

Thank you very much!

Best,
Xiao

**Comment by PeterXiaoGuo** [comment]
Thank you very much!

The following tips may help:

For non-sudo user, when run 
`./build.sh` 
command, it may face no nvcc error:
run the following command in linux may help:
`export PATH=${PATH}:/usr/local/cuda/bin`

For people who face g++ compiling error, installed g++ 6.4 and updates the symbolic links in /usr/bin will help.

thank you very much

**Comment by cutecy** [comment]
Where is build.sh file please?

**Comment by HuaqiangWei** [comment]
> Where is build.sh file please?
Have you  find the build.sh file? I can't find the module folder。

**Comment by PeterXiaoGuo** [comment]
> Where is build.sh file please?

> > Where is build.sh file please?
> > Have you  find the build.sh file? I can't find the module folder。

@cutecy  @HuaqiangWei 

I check the history and it's deleted by the author. Maybe the new version don't need it anymore.
