### ISSUE TITLE
Could you please upload the weight folder? 

### ISSUE THREAD

**Issue by PeterXiaoGuo** [ternaus/TernausNetV2#3]
Hi,

Thank you very much for sharing the original codes for TernausNetV2.

During reproducing the result, could you please share the weight folder, otherwise, even the example jupyter notebook cannot re-run and throws error **"FileNotFoundError: [Errno 2] No such file or directory: 'weights/deepglobe buildings.pt'"**

thank you very much,

Xiao

**Comment by ternaus** [comment]
Sorry about this.

I updated readme, you can find a link to the weights at the bottom of the readme, near the link to the demo example.
