### ISSUE TITLE
contour creation

### ISSUE THREAD

**Issue by A-Jacobson** [ternaus/TernausNetV2#8]
Hey Vladimir,

In one of the other issues you shared your contour creation function:

```python
def create_contour(labels):
    mask = labels.copy()
    mask[mask > 0] = 1
    dilated = binary_dilation(mask, iterations=4)
    mask_wl = watershed(dilated, labels, mask=dilated, watershed_line=True)
    mask_wl[mask_wl > 0] = 1
    contours = dilated - mask_wl
    contours = binary_dilation(contours, iterations=3)
    return contours
```

Could you please also share what's going on with the `binary_dilation` function? I don't believe that's the standard skimage function. Are you trying to adaptively set the dilation amount like the winners of the 2018 DSB did?

**Comment by ternaus** [comment]
```
from scipy.ndimage import binary_dilation, binary_erosion, binary_closing
```

**Comment by robeson1010** [comment]
I found the code you provided was not correct . It should be

def create_contour(labels):
    mask = labels.copy()
    mask[mask > 0] = 1
    dilated = binary_erosion(mask, iterations=4)
    mask_wl = watershed(dilated, labels, mask=dilated, watershed_line=True)
    mask_wl[mask_wl > 0] = 1
    contours = dilated - mask_wl
    contours = binary_dilation(contours, iterations=3)
    return contours

My question is  if we got the cotours, how to get the binary mask in which we predict areas of an image where different objects touch or very close to each other.

**Comment by robeson1010** [comment]
@ternaus

**Comment by ternaus** [comment]
This function should directly return such a binary mask.

**Comment by antran89** [comment]
@antran89 follow this thread

**Comment by antran89** [comment]
@ternaus Thank you for your code. But the code cannot produce any building touches with your functions on Shanghai and Khartoum dataset.

Building mask of an image (`MUL-PanSharpen_AOI_4_Shanghai_img125`):

![mul-pansharpen_aoi_4_shanghai_img125.png](https://user-images.githubusercontent.com/2399449/48663187-5594b280-eac7-11e8-9c07-ecbdf1033ab7.png)

Building touches mask:
![mul-pansharpen_aoi_4_shanghai_img125](https://user-images.githubusercontent.com/2399449/48663203-a4dae300-eac7-11e8-8d1d-5f8b7e063c5f.png)

**Comment by ternaus** [comment]
Your mask has values [0, 255]. Try to rescale it to [0, 1]

**Comment by ternaus** [comment]
```
from skimage.measure import label
contour = create_contour(label(mask))
```
should do the job.

**Comment by antran89** [comment]
@ternaus Thank you for your quick responses. Happy weekend. Without your help, I could not reproduce the mask.
Oh, we need to use another function for the input mask.

![mul-pansharpen_aoi_4_shanghai_img125](https://user-images.githubusercontent.com/2399449/48668694-008c8700-eb2f-11e8-9e6c-d6324923675f.png)
